#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Proofread Pancake

# Short bio or description (displayed in the header)
description: Save time and do more of what you really want to do. Allow me to proofread your work -- you'll be glad you did!

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent lobortis lacus nec porttitor facilisis. Aenean at ante nec turpis cursus auctor et et enim. Praesent vestibulum erat vel nunc efficitur, id eleifend justo molestie. Suspendisse consequat placerat varius. Integer sit amet ornare magna. Suspendisse viverra ipsum nec leo euismod dignissim. Integer aliquet erat eget tempus rhoncus. Donec fringilla et quam vitae suscipit. Proin eget justo nunc. Quisque nec aliquam augue. Suspendisse vestibulum id magna vel pharetra. Vestibulum faucibus pharetra ligula, et tincidunt nisi dignissim vel. Maecenas id euismod tortor. Donec vel lobortis lorem. Praesent eu sem quis mauris interdum hendrerit in facilisis odio. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Vestibulum non nibh lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer pretium mi id sapien venenatis commodo. Nunc pulvinar non tellus nec imperdiet. Nulla porttitor rutrum faucibus. Maecenas in sapien magna. Maecenas nec volutpat urna. Aenean ullamcorper scelerisque ipsum, vel egestas felis ornare ac. Maecenas tellus lacus, elementum a libero a, ultrices pellentesque urna.

Nulla non consectetur sapien, venenatis iaculis tellus. Suspendisse nisl nisl, rhoncus nec mi vitae, auctor dignissim metus. Phasellus sit amet velit a orci molestie vehicula. Phasellus efficitur diam et lectus sollicitudin posuere. Vivamus elementum augue ac pharetra rutrum. Vivamus vitae imperdiet lacus. Suspendisse non ultrices ante. Duis ultrices, metus a pellentesque condimentum, quam ipsum ullamcorper nisl, vel fermentum est justo eget turpis. In sit amet urna nibh. Ut interdum, magna id pulvinar sollicitudin, dolor lectus sodales ligula, a tristique sem enim non velit. Nulla molestie odio ac ullamcorper congue. Maecenas erat massa, malesuada sed ligula eget, placerat accumsan augue. Morbi non risus dapibus, congue odio nec, rutrum tortor.

Cras sed efficitur quam. Duis sit amet mauris eu erat lacinia euismod. Fusce hendrerit condimentum quam sit amet rhoncus. Sed egestas turpis ut enim porttitor, vel ultrices velit euismod. Proin nisi lectus, porttitor eget tincidunt ut, aliquet eget felis. Phasellus eget velit gravida, pharetra diam et, fermentum diam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque luctus id nibh non blandit. Phasellus sit amet elementum libero, laoreet molestie dolor. Nulla dictum metus in accumsan laoreet. Integer rutrum tincidunt felis, sit amet volutpat velit volutpat vel.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars0.githubusercontent.com/u/8955802?s=400&u=75bf22011cf0b8c33cd03a1acc717e31c937e79a&v=4

#
# Flags below are optional
#

# remote_theme: benbalter/retlab
# remote_theme: mmistakes/minimal-mistakes

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: barryclark/jekyll-now
  instagram:
  linkedin:
  pinterest:
  rss: rss
  twitter: 
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
